var urlVector='https://api.maptiler.com/maps/<>/style.json?key=eIgS48TpQ70m77qKYrsx';var urlRaster='https://api.maptiler.com/maps/<>/tiles.json?key=eIgS48TpQ70m77qKYrsx';var activeId='';var map,mapRaster,mapRasterLayer;function mapPreview(){var syncMutex=false;var center=[[-122.445600,37.789508,3],[-73.997291,40.725438,3],[2.294433,48.858288,1],[8.541147,47.376333,3]][Math.floor(Math.random()*4)];var fitBounds=null;if(window.bbox&&window.bbox.length==4){fitBounds=window.bbox;}
if(mapboxgl.supported()){mapboxgl.setRTLTextPlugin('https://cdn.klokantech.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.1.2/mapbox-gl-rtl-text.js');map=new mapboxgl.Map({attributionControl:false,container:'map',center:[center[0],center[1]],zoom:center[2]});if(fitBounds){map.fitBounds([[fitBounds[0],fitBounds[1]],[fitBounds[2],fitBounds[3]]],{animate:false,padding:20,maxZoom:5});}
map.setMaxBounds(null);map.addControl(new mapboxgl.NavigationControl());map.addControl(new mapboxgl.AttributionControl());map.autodetectLanguage();setTimeout(function(){syncMutex=true;mapRaster.getView().setCenter(ol.proj.fromLonLat([map.getCenter().lng,map.getCenter().lat]));mapRaster.getView().setZoom(map.getZoom()+1);syncMutex=false;},0);}else{document.getElementById('map').innerHTML='<div style="position:absolute;top:120px;width:100%;text-align:center;">Vector map requires WebGL support</div>';}
mapRaster=new ol.Map({target:'map-raster',controls:[new ol.control.Rotate({className:'mt-button-last',autoHide:false,}),new ol.control.Zoom({className:'mt-button'}),new ol.control.Attribution({collapsible:false,})],view:new ol.View({center:ol.proj.fromLonLat([center[1],center[0]]),zoom:center[2]+1,minZoom:1})});switchMap('streets',true);if(map){map.on('move',function(){if(syncMutex)return;syncMutex=true;mapRaster.getView().setCenter(ol.proj.fromLonLat([map.getCenter().lng,map.getCenter().lat]));mapRaster.getView().setZoom(map.getZoom()+1);syncMutex=false;});mapRaster.getView().on('change',function(){if(syncMutex)return;syncMutex=true;map.setZoom(mapRaster.getView().getZoom()-1);map.setCenter(ol.proj.toLonLat(mapRaster.getView().getCenter()));syncMutex=false;});document.getElementById('map-type').addEventListener('change',switchType);}else{var switcherWrap=document.getElementsByClassName('map-type-wrap')[0];var mv=document.getElementById('map');var mr=document.getElementById('map-raster');document.getElementById('map-type-vector').classList.toggle('b');document.getElementById('map-type-raster').classList.toggle('b');switcherWrap.style.display='none';mv.style.display='none';mr.style.display='block';isRaster=true;mapRaster.updateSize();}
if(map){map.on('moveend',function(){updateHash();});}else{mapRaster.on('moveend',function(){updateHash();});}
isFullscreen=document.querySelector('.map-wrap').classList.contains('fullscreen');setTimeout(function(){if(map)map.resize();mapRaster.updateSize();updateHash();},0);parseHash();loadGeocoder();}
var switchType=function(){var switcher=document.getElementById('map-type');var mv=document.getElementById('map');var mr=document.getElementById('map-raster');document.getElementById('map-type-vector').classList.toggle('b');document.getElementById('map-type-raster').classList.toggle('b');if(mv.style.display=='none'){switcher.innerHTML='switch to raster tiles';mv.style.display='block';mr.style.display='none';isRaster=false;if(map)map.resize();}else{switcher.innerHTML='switch to vector tiles';mv.style.display='none';mr.style.display='block';isRaster=true;mapRaster.updateSize();}
updateHash();};var activeLanguage='',isFullscreen,isRaster;function updateHash(){if(!isFullscreen){if(location.hash.length>1)location.hash='';return;}
var hash=[activeId,activeLanguage,isRaster?'raster':'vector'];if(map){var center=map.getCenter(),zoom=Math.round(map.getZoom()*100)/100,precision=Math.ceil((zoom*Math.LN2+Math.log(512/360/0.5))/Math.LN10),m=Math.pow(10,precision),lng=Math.round(center.lng*m)/m,lat=Math.round(center.lat*m)/m,bearing=map.getBearing(),pitch=map.getPitch();hash.push(zoom,lng,lat);if(bearing||pitch){hash.push(bearing.toFixed(2));if(pitch)hash.push(pitch.toFixed(1));}}else{var center=ol.proj.toLonLat(mapRaster.getView().getCenter()),zoom=mapRaster.getView().getZoom();hash.push(zoom,center.lng,center.lat);}
location.hash=hash.join('/');}
function parseHash(){var hash=location.hash.substr(1).split('/');if(hash[0]){switchMap(hash[0]);}
if(hash[1]){document.getElementById('map-language').value=activeLanguage=hash[1];if(map)map.setLanguage(hash[1]);}
if(hash[2]){if(hash[2]=='raster'&&map){switchType();document.getElementById('map-type').checked=true;}}
if(hash.length>=6){if(map){map.jumpTo({center:[+hash[4],+hash[5]],zoom:+hash[3],bearing:+(hash[6]||0),pitch:+(hash[7]||0)});}else{mapRaster.getView().setCenter(ol.proj.fromLonLat([+hash[5],+hash[4]]));mapRaster.getView().setZoom(+hash[3]);}}}
function updateRaster(){fetch(urlRaster.replace('<>',activeId)).then(function(data){return data.json()}).then(function(json){url=json.tiles[0];if(window.devicePixelRatio>1){url=url.replace('.png','@2x.png').replace('.jpg','@2x.jpg');}
if(mapRasterLayer){mapRaster.removeLayer(mapRasterLayer);}
mapRasterLayer=new ol.layer.Tile({source:new ol.source.XYZ({url:url,tileSize:[512,512],attributions:json.attribution})});mapRaster.addLayer(mapRasterLayer);});}
function switchMap(id,opt_dontUpdateHash){if(activeId!=id){activeId=id;if(map){map.setStyle(urlVector.replace('<>',id));var backgroundColor='#f2f3f6';if(activeId=='streets'){backgroundColor='rgba(252, 247, 229, 1)';}else if(activeId=='hybrid'){backgroundColor='#333';}else if(activeId=='topo'){backgroundColor='rgba(232, 230, 223, 1)';}else if(activeId=='basic'){backgroundColor='hsl(47, 26%, 88%)';}
document.getElementById('map').style.backgroundColor=backgroundColor;map.once('styledata',function(e){var tmpStaticUrl;var randomNumber=Math.round(10000*Math.random()).toString()
if(activeId=='streets'){tmpStaticUrl='/img/cloud/maps/streets-static-1024.png';}else if(activeId=='hybrid'){tmpStaticUrl='/img/cloud/maps/hybrid-static-1024.jpg';}else if(activeId=='topo'){tmpStaticUrl='/img/cloud/maps/topo-static-1024.png';}else if(activeId=='basic'){tmpStaticUrl='/img/cloud/maps/basic-static-1024.png';}
if(tmpStaticUrl){map.addSource('tmp-static-source-'+randomNumber,{'type':'image','url':tmpStaticUrl,'coordinates':[[-180,85.05],[180,85.05],[180,-85.05],[-180,-85.05]]});map.addLayer({'id':'tmp-static-'+randomNumber,'source':'tmp-static-source-'+randomNumber,'maxzoom':7,'type':'raster'},map.getStyle().layers[1].id);var listener=function(e){if(map.loaded()&&map.areTilesLoaded()&&map.getLayer('tmp-static-'+randomNumber)){map.removeLayer('tmp-static-'+randomNumber);map.removeSource('tmp-static-source-'+randomNumber);map.off('render',listener);}};map.on('render',listener);}});}}
updateRaster(id);if(!opt_dontUpdateHash){updateHash();}}
function loadGeocoder(){if(maptiler&&maptiler.Geocoder){var geocoder=new maptiler.Geocoder({input:'map-geocoder',key:'eIgS48TpQ70m77qKYrsx'});geocoder.on('select',function(item){let bbox=item.bbox;if(bbox&&map){map.fitBounds([[bbox[0],bbox[1]],[bbox[2],bbox[3]]]);}});}}